spring:
  profiles:
    active: docker
redisqueue:
  name: "bid:redisqueue"
  host-name: "localhost"
  port: 6379

---
spring:
  profiles: default
  application:
      name: cash-flow-service
  datasource:
    url: jdbc:postgresql://localhost:5432/usercashflowdb?user=postgres&password=password
    driver-class-name: org.postgresql.Driver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  application:
      name: cash-flow-service
  datasource:
    url: jdbc:postgresql://localhost:5434/usercashflowdb?user=postgres&password=password
    driver-class-name: org.postgresql.Driver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/