spring:
  profiles:
    active: default

---
spring:
  profiles: default
  application:
      name: gateway-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

---
spring:
  profiles: docker
  application:
    name: gateway-service

eureka:
  instance:
    preferIpAddress: true
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8080